const DEFAULT_JOBS = [
  {
    id: "job_001",
    logoBg: "#0f172a",
    logoText: "G",
    company: "Genpact",
    verified: true,
    title: "Process Associate - Backend Operations",
    walkinDateDisplay: "12 Oct - 15 Oct 2026",
    walkinDate: "2026-10-12",
    urgency: "Urgent Walk-In",
    package: "₹2.5 LPA - ₹3.5 LPA",
    location: "Noida",
    areaDetail: "Sector 135, Noida",
    workingDays: "5 Days Working, US Night Shift",
    experience: "0-2 Years (Freshers Eligible)",
    criteria: "Any Graduate. Excellent English communication required. Basic knowledge of MS Excel is a plus.",
    applyUrl: "https://careers.genpact.com",
    rounds: "Aptitude Test -> HR Screening -> Operations Manager Round",
    category: "Process Analyst",
    walkinTime: "11:00 AM - 2:00 PM",
    contactPerson: "Priya Sharma (HR)",
    venue: "Genpact, Plot 22, IT SEZ, Sector 135, Noida, Uttar Pradesh",
    googleMapsUrl: "https://maps.google.com/?q=Genpact+Sector+135+Noida",
    documentsRequired: "Updated Resume (2 copies), Aadhar Card, PAN Card, and passport size photographs."
  },
  {
    id: "job_002",
    logoBg: "#2563eb",
    logoText: "C",
    company: "Concentrix",
    verified: true,
    title: "International Voice Process - Customer Support",
    walkinDateDisplay: "14 Oct - 18 Oct 2026",
    walkinDate: "2026-10-14",
    urgency: "Hiring Fast",
    package: "₹3.0 LPA - ₹4.5 LPA",
    location: "Gurugram",
    areaDetail: "DLF Cyber City, Gurugram",
    workingDays: "5 Days Working, Rotational Shift",
    experience: "1-4 Years",
    criteria: "Undergraduate / Graduate. Fluent verbal communication in English. Prior experience in BPO voice process preferred.",
    applyUrl: "https://careers.concentrix.com",
    rounds: "HR Round -> Voice & Accent Test -> VNA Versant -> Final Client Round",
    category: "Customer Support",
    walkinTime: "12:00 PM - 4:00 PM",
    contactPerson: "Rahul Verma (Talent Acquisition)",
    venue: "Concentrix, Building 14, DLF Cyber City, Phase 3, Gurugram, Haryana",
    googleMapsUrl: "https://maps.google.com/?q=Concentrix+Cyber+City+Gurugram",
    documentsRequired: "Resume, Govt ID proof, Relieving letter (if experienced), and Salary slips of last 3 months."
  },
  {
    id: "job_003",
    logoBg: "#059669",
    logoText: "P",
    company: "Provana",
    verified: true,
    title: "Junior Process Analyst - BPM",
    walkinDateDisplay: "Tomorrow",
    walkinDate: "2026-09-20",
    urgency: "Walk-In",
    package: "₹3.5 LPA - ₹5.0 LPA",
    location: "Noida",
    areaDetail: "Sector 62, Noida",
    workingDays: "Fixed Day Shift",
    experience: "Fresher",
    criteria: "B.Tech / B.E (2025/2026 Batch) or Any Graduate. Strong analytical skills and problem-solving mindset.",
    applyUrl: "https://www.provana.com/careers",
    rounds: "Written Test -> Technical Assessment -> HR Interview",
    category: "Process Analyst",
    walkinTime: "10:00 AM - 1:00 PM",
    contactPerson: "Neha Singh",
    venue: "Provana India, Logix Cyber Park, Sector 62, Noida",
    googleMapsUrl: "https://maps.google.com/?q=Logix+Cyber+Park+Noida",
    documentsRequired: "Hard copy of Resume, Provisional Degree/Mark sheets, and 2 Passport size photos."
  },
  {
    id: "job_004",
    logoBg: "#db2777",
    logoText: "T",
    company: "TCS",
    verified: false,
    title: "IT Support Engineer / System Admin",
    walkinDateDisplay: "Every Saturday",
    walkinDate: "2026-10-17",
    urgency: "Weekend Drive",
    package: "₹4.0 LPA",
    location: "Gurugram",
    areaDetail: "Sector 59, Gurugram",
    workingDays: "5 Days Working, Day Shift",
    experience: "0-1 Years",
    criteria: "B.Tech/BCA/MCA. Basic knowledge of Networking, Windows/Linux OS, and hardware troubleshooting.",
    applyUrl: "https://www.tcs.com/careers",
    rounds: "Aptitude -> Technical Technical Discussion -> HR",
    category: "IT / Software",
    walkinTime: "9:30 AM - 12:30 PM",
    contactPerson: "TCS Recruitment Team",
    venue: "TCS, Pioneer Square, Sector 59, Gurugram, Haryana",
    googleMapsUrl: "https://maps.google.com/?q=TCS+Pioneer+Square+Gurugram",
    documentsRequired: "TCS Application Form printout, Updated Resume, Original ID Proof."
  },
  {
    id: "job_005",
    logoBg: "#9333ea",
    logoText: "H",
    company: "HCLTech",
    verified: true,
    title: "HR Executive - Talent Acquisition",
    walkinDateDisplay: "18 Oct 2026",
    walkinDate: "2026-10-18",
    urgency: "Walk-In",
    package: "₹2.8 LPA - ₹4.0 LPA",
    location: "Noida",
    areaDetail: "Sector 126, Noida",
    workingDays: "Fixed Day Shift",
    experience: "1-3 Years",
    criteria: "MBA in HR or equivalent. Experience in end-to-end recruitment, sourcing through portals, and vendor management.",
    applyUrl: "https://www.hcltech.com/careers",
    rounds: "Initial HR Screening -> Managerial Round -> Final HR Review",
    category: "HR & Recruitment",
    walkinTime: "11:00 AM - 3:00 PM",
    contactPerson: "Amit Kumar",
    venue: "HCLTech Campus, Sector 126, Noida, Uttar Pradesh",
    googleMapsUrl: "https://maps.google.com/?q=HCLTech+Sector+126+Noida",
    documentsRequired: "Updated CV, Last 3 months Salary Slips, Adhaar Card."
  }
];
