const DEFAULT_JOBS = [

    {
    id: "job_001",
    logoBg: "#2563eb",
    logoText: "M",
    company: "MTAP Technologies",
    verified: true,
    title: "Trainee - Software Engineer (Frontend / Backend / QA)",
    walkinDateDisplay: "Ongoing Hiring",
    walkinDate: "2026-09-20",
    urgency: "Hiring Fast",
    package: "Not Disclosed",
    location: "Gurugram",
    areaDetail: "Udyog Vihar Phase 4, Gurugram",
    workingDays: "5 Days Working, Day Shift",
    experience: "Fresher",
    criteria: "B.Tech/MCA/BCA. Basic knowledge of JavaScript, React, Java, or Software Testing depending on the role.",
    applyUrl: "https://www.mtap.in/contactus/",
    rounds: "Online Assessment -> Technical Interview -> HR Round",
    category: "IT / Software",
    walkinTime: "10:30 AM - 4:00 PM (Subject to shortlist)",
    contactPerson: "Talent Acquisition Team",
    venue: "ONWARD Workspaces, 27, Phase IV, Udyog Vihar, Sector 18, Gurugram, Haryana - 122015",
    googleMapsUrl: "https://maps.google.com/?q=ONWARD+Workspaces+Udyog+Vihar+Sector+18+Gurugram",
    documentsRequired: "Updated Resume, Provisional/Degree Certificate, and Aadhar Card."
  },
    
{
    id: "job_002",
    logoBg: "#8b5cf6",
    logoText: "X",
    company: "Xziant Communications",
    verified: true,
    title: "Search Engine Optimization Executive And Content Writer",
    walkinDateDisplay: "1st Sep - 30th Sep",
    walkinDate: "2026-09-01",
    urgency: "Walk-In",
    package: "Not Disclosed",
    location: "Noida",
    areaDetail: "Sector 63, Noida",
    workingDays: "DAY / NIGHT Shift",
    experience: "Experience Not Mentioned",
    criteria: "Knowledge of SEO and Content Writing.",
    applyUrl: "https://xziant.com/",
    rounds: " Technical Round ",
    category: "IT / Software",
    walkinTime: "06:30 PM - 8:30 PM",
    contactPerson: "Vidhi Chaudhary (8448610952)",
    venue: "A-202, Block - A, Sector - 63, Noida",
    googleMapsUrl: "https://maps.google.com/?q=A-202+Sector+63+Noida",
    documentsRequired: "Updated Resume, Aadhar Card, and Passport Size Photos."
  },
{
    id: "job_003",
    logoBg: "#10b981",
    logoText: "H",
    company: "HangingPanda Pvt. Ltd.",
    verified: true,
    title: "IT Sales Intern",
    walkinDateDisplay: "Ongoing Hiring",
    walkinDate: "2026-09-20",
    urgency: "5 Openings",
    package: "Up to ₹10,000 / Month (Stipend)",
    location: "Noida",
    areaDetail: "Sector 63, Noida",
    workingDays: "Day Shift",
    experience: "Fresher",
    criteria: "Bachelor’s degree in Business, Marketing, or IT. Strong communication and knowledge of lead generation, cold calling, and IT sales.",
    applyUrl: "https://hangingpanda.com/career",
    rounds: "HR Screening -> Sales/Managerial Interview",
    category: "IT / Software",
    walkinTime: "11:00 AM - 4:00 PM",
    contactPerson: "HR Department",
    venue: "HangingPanda Pvt. Ltd., B-64, B Block, Sector 63, Noida, Uttar Pradesh 201301",
    googleMapsUrl: "https://maps.google.com/?q=HangingPanda+Sector+63+Noida",
    documentsRequired: "Updated Resume, College ID/Degree, and Aadhar Card."
  },

    {
    id: "job_004",
    logoBg: "#059669",
    logoText: "P",
    company: "Provana",
    verified: true,
    title: "Process Executive - Legal/Backend Operations",
    walkinDateDisplay: "Monday to Friday",
    walkinDate: "2026-09-22",
    urgency: "Hiring Fast",
    package: "₹2.5 LPA ",
    location: "Noida",
    areaDetail: "Sector 62, Noida",
    workingDays: "5 Days Working, US Night Shift",
    experience: "0-2 Years (Freshers Eligible)",
    criteria: "Any Graduate (B.A/B.Com/B.B.A preferred). Good reading and comprehension skills for legal documents. US Shift readiness.",
    applyUrl: "https://www.provana.com/careers",
    rounds: "Aptitude -> Typping Test -> HR Round -> Manager Round",
    category: "Process Analyst",
    walkinTime: "11:00 AM - 4:00 PM",
    contactPerson: "Provana HR Team",
    venue: "Provana India, Logix Cyber Park, Tower C, Sector 62, Noida",
    googleMapsUrl: "https://maps.google.com/?q=Provana+A68+Sector+64+Noida",
    documentsRequired: "Updated Resume, Aadhar Card, PAN Card, and Educational Certificates."
  },
    
{
    id: "job_005",
    logoBg: "#8b5cf6",
    logoText: "X",
    company: "Xziant Communications",
    verified: true,
    title: "Business Development Associate (BDA)",
    walkinDateDisplay: "1st Sep - 30th Sep",
    walkinDate: "2026-09-01",
    urgency: "Walk-In",
    package: "₹15,000 - ₹23,000 Per Month",
    location: "Noida",
    areaDetail: "Sector 63, Noida",
    workingDays: "6 Days Working, Day + Night Shift",
    experience: "0 to 3",
    criteria: "Good communication skills required. Interested in Business Development and Sales.",
    applyUrl: "https://xziant.com/",
    rounds: "Direct HR Round",
    category: "Customer Support",
    walkinTime: "9:30 AM - 5:30 PM",
    contactPerson: "Vidhi Chaudhary (8448610952)",
    venue: "A-202, Block - A, Sector - 63, Noida",
    googleMapsUrl: "https://maps.google.com/?q=A-202+Sector+63+Noida",
    documentsRequired: "Updated Resume, Aadhar Card, and Passport Size Photos."
  },
  {
    id: "job_006",
    logoBg: "#db2777",
    logoText: "T",
    company: "TCS",
    verified: false,
    title: "IT Support Engineer / System Admin",
    walkinDateDisplay: "Every Saturday",
    walkinDate: "2026-10-17",
    urgency: "Weekend Drive",
    package: "₹4.0 LPA",
    location: "Gurugram",
    areaDetail: "Sector 59, Gurugram",
    workingDays: "5 Days Working, Day Shift",
    experience: "0-1 Years",
    criteria: "B.Tech/BCA/MCA. Basic knowledge of Networking, Windows/Linux OS, and hardware troubleshooting.",
    applyUrl: "https://www.tcs.com/careers",
    rounds: "Aptitude -> Technical Technical Discussion -> HR",
    category: "IT / Software",
    walkinTime: "9:30 AM - 12:30 PM",
    contactPerson: "TCS Recruitment Team",
    venue: "TCS, Pioneer Square, Sector 59, Gurugram, Haryana",
    googleMapsUrl: "https://maps.google.com/?q=TCS+Pioneer+Square+Gurugram",
    documentsRequired: "TCS Application Form printout, Updated Resume, Original ID Proof."
  },
  {
    id: "job_007",
    logoBg: "#9333ea",
    logoText: "H",
    company: "HCLTech",
    verified: true,
    title: "HR Executive - Talent Acquisition",
    walkinDateDisplay: "18 Oct 2026",
    walkinDate: "2026-10-18",
    urgency: "Walk-In",
    package: "₹2.8 LPA - ₹4.0 LPA",
    location: "Noida",
    areaDetail: "Sector 126, Noida",
    workingDays: "Fixed Day Shift",
    experience: "1-3 Years",
    criteria: "MBA in HR or equivalent. Experience in end-to-end recruitment, sourcing through portals, and vendor management.",
    applyUrl: "https://www.hcltech.com/careers",
    rounds: "Initial HR Screening -> Managerial Round -> Final HR Review",
    category: "HR & Recruitment",
    walkinTime: "11:00 AM - 3:00 PM",
    contactPerson: "Amit Kumar",
    venue: "HCLTech Campus, Sector 126, Noida, Uttar Pradesh",
    googleMapsUrl: "https://maps.google.com/?q=HCLTech+Sector+126+Noida",
    documentsRequired: "Updated CV, Last 3 months Salary Slips, Adhaar Card."
  }
];
